### PR TITLE
Adding the ability for SkinsSidebar to update the count when filtering is updated

### PR DESCRIPTION
**Pull request by nalham**
Currently, counts do not get adjusted when filtering, this allows counts to update accordingly.

- [x] Update Functionality 
  - New functionality shown in this video: https://photos.app.goo.gl/xDySNZK45ZKhbCFb2
- [x] Update Unit Tests
  - [x] `<SkinsSidebar /> should render correctly`
  - [x] `<SkinsSidebar /> should toggle between RP Total and Skins Count`

### CODE REVIEW

**Comment by s-coimbra21** [comment]
Hi friend, thanks for the pull request.

Out of curiosity, may I ask why you're submitting this now? You should know that this app is basically deprecated due to the official skins tab that Riot added on the official client.

**Comment by nalham** [comment]
1. I needed a React project to learn on.
2. I still use this app over their tab and it's been a feature I've been meaning to look into since I downloaded at first release. (they also have this same problem in their implementation)

**Comment by s-coimbra21** [comment]
Alright, I'll take a look at this tomorrow.

**Review by s-coimbra21 — APPROVED** [review]

**Comment by nalham** [comment]
@s-coimbra21 thanks for the review, to merge this, do we have to increment the version number?

**Comment by xadamxk** [comment]
Do you plan on merging this? @s-coimbra21

**Comment by nalham** [comment]
Ping @s-coimbra21 , I can back merge or update if needed

**Comment by nalham** [comment]
This application no longer works with the latest client, closing PR.

**Pull request closed without merging**
